### ISSUE TITLE
How to change the  out image size?

### ISSUE THREAD

**Issue by Christy-Luo** [Prinsphield/GeneGAN#4]
I try to change nhwc = [64,64,64,3] in dataset.py, but this didn't work well.

**Comment by Prinsphield** [comment]
For example, `nhwc = [64,128,128,3]` is for 128 * 128 images. To  make GeneGAN still effective for higher resolution images, you might also need to adjust the network structure as well, such as the width and depth of discriminator, encoder and decoder.

**Comment by Christy-Luo** [comment]
But I don't know how to change the network structure.
Should I need to change the values in the function "discriminator": [4,4,3,128], [4,4,128,256], [4,4,256,512],[4,4,512,512]? or in the function "splitter" or "joiner" such as [4,4,3,128], [4,4,128,256], etc.?

**Comment by Prinsphield** [comment]
Yes. You can adjust those parameters, or add additional layers.
