### ISSUE TITLE
Where can I see the checkpoint path?

### ISSUE THREAD

**Issue by abd-ozos** [Prinsphield/GeneGAN#8]
Hello, Thanks for sharing your code.
I would like to know the checkpoint path so that I would be able to find the training process. Thank you.

**Comment by Prinsphield** [comment]
Sorry, we did not provide the pre-trained model.

**Comment by abd-ozos** [comment]
Thank you for your response. It's almost taking more than one day for training.  I am  training the model using CPU only. Is there any possibilities to increase the speed of training apart from GPU.?

**Comment by Prinsphield** [comment]
I think it is better to use a GPU for training. You may consider using google's google colab, where you can use one free GPU there.
